### ISSUE TITLE
Custom mishaps in API

### ISSUE THREAD

**Issue by slava110** [gamma-delta/HexMod#126]
Hi. I'm working on my addon for Hex Casting. Recently I wanted to create a custom mishap for my spell (if caster is the same entity as target it should throw a mishap) but it looks like [mishaps are sealed](https://github.com/gamma-delta/HexMod/blob/71a0b11d2544702430a4403432dbb83bf6d86246/Common/src/main/java/at/petrak/hexcasting/api/spell/mishaps/Mishap.kt#L26). Is it intended? What should I do instead of throwing custom mishaps then?

**Comment by gamma-delta** [comment]
Whoops, those shouldn't be sealed 😅
I would recommend waiting a bit to work on your addon though, because we're
releasing a 1.0 update and that's where all the breaking API changes are
gonna go. I'll fix that on that branch right away, and if you're feeling
brave you can try basing your addon off of that branch.
