### ISSUE TITLE
Casting bypasses FTB Chunks protection

### ISSUE THREAD

**Issue by kaipuma** [gamma-delta/HexMod#136]
Playing on a server that uses the [Direwolf20 1.18 pack](https://www.feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18), and I noticed that I could break a block in another person's claim with that spell, even though that's intended to be forbidden by the [FTB Chunks](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge) mod.

**Comment by KirinDave** [comment]
It is also customary for mods to refuse to teleport something or blink someone while in a chunk owned by someone else, to avoid "a flood of invaders" or "blinking through a wall or past an untouchable door".

**Comment by Ant-Redstone** [comment]
Can confirm that's still not fixed, claimed chunks by FTB still can be broken, I'v tested it on official [AOF5 ](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5)servers

**Comment by yrsegal** [comment]
This would be... difficult to fix. Architectury, for some reason, isn't using the builtin fabric events, which means that our hook - which checks the event as it should - just... doesn't get stopped by their code.

Rather than cancel the event, they instead mix directly into ServerPlayerGameMode, preventing the breaking only if done directly by a player. Which on the one hand, makes sense to a certain extent... but I don't think this is really on us?
