### ISSUE TITLE
[BUG] Trinkets cannot recharge themselves

### ISSUE THREAD

**Issue by KirinDave** [gamma-delta/HexMod#154]
I have a trinket with a recharge function. While holding another item, it can recharge that item successfully. But if it tries to recharge itself (i.e., I hold the trinket in the offhand with no other items in hand) it fails, claiming, "Recharge Item needs a rechargeable item in the other hand but got nothing." 

Wiresegal said this was surprising and I should report it.

**Comment by SnazzGass** [comment]
trinkets also seem to be unable to erase themselves. And they also don't seem to be able to write to themselves, 

Trying to use a trinket to cast Craft Trinket results in
"Craft Trinket needs Trinket in the other hand but got nothing"
instead of
"Craft Trinket needs a place to write iotas to in the other hand but got 1x [Trinket]"
