### ISSUE TITLE
Game panics upon trying to create a world (Quilt/Fabric)

### ISSUE THREAD

**Issue by SuperKnux** [gamma-delta/HexMod#219]
I've figured out that it's Hex Casting and Cardinal Components API causing this issue.
The thing is, with the other mods I have, I have no clue if any other mods (Other than Hex Casting, somehow???) could be nesting a version of CCA that could be causing the game to panic, as the game runs fine with just Hex Casting and it's dependencies. 

[https://mclo.gs/oZVlZNZ](url) Link to a log that I had, with an attempt to run the game with only *half* of the mods in the modpack, running on Fabric. As you can see, the world spawn generation gets to 16% before the game panics and spits out a bunch of errors (seemingly all the same,) with Hex Casting being among them.

**Comment by gattsuru** [comment]
In the short term, running Cardinal Components 4.1.4 will solve this issue.  There is a fix for 0.9.2 that allows use of CC 4.2.0, but it hasn't been released yet.

Do be warned that there's a separate issue with HexCasting 0.9.2 that causes a crash on EdifySapling, which likewise will be fixed with 0.9.2.
