### ISSUE TITLE
some text is completely unreadable on medium gui size

### ISSUE THREAD

**Issue by Hate9** [gamma-delta/HexMod#442]
at 1080p, the guidebook contains *many* pages which are *completely* unreadable at medium GUI size.

I understand that apparently lots of people use the larger GUI sizes, but it seems like a problem, to me, that even *slightly* smaller-than-expected GUI settings makes a good nunber of pages *entirely* unreadable.

This could be fixed either by changing the font rendering (hard, not yoyr job) or by slightly reordering the pages so the text isn't absolutely tiny. I literally haven't seen patchouli books with text this small (or variable) until this mod.

**Comment by gamma-delta** [comment]
Unfortunately we're kind of running into Patchouli issues ... and Minecraft font rendering issues in general. Patchouli is good for mod-style documentation but not good for "an actual programming language," which is what this mod is ...

Many discussions have been had about hex's terrible terrible documentation and to be honest I don't know what to do. I'm very tempted to have the book just send people to a website; the browser version of the book is much more usable anyways.

I'm going to leave this open because I really haven't fixed it, but also, don't hold your breath.

**Comment by Hate9** [comment]
Yeah that's kinda what I thought. It's an extremely difficult and annoying problem.
Personally, I definitely really like that there's an ingame book, and how it's integrated with the advancements, but I can definitely see there being logic to at least including a link to the web version somewhere.

**Comment by Hate9** [comment]
Oh, I didn't realize you can upscale the book separately from the main page. That makes this problem significantly less bad.

**Comment by gamma-delta** [comment]
Alright then ... I believe Forge has a hacky patch fix to this (letting text be anti-aliased in certain cases) but still, that's Patchi's impetus to fix it.
