### ISSUE TITLE
(Suggestion) Make it possible to exit the running hex with Hermes' Gambit.

### ISSUE THREAD

**Issue by TheOriginalArkless** [gamma-delta/HexMod#521]
I found no way of conditionally exiting the current hex. (Did I miss something?)
If I use Augur's Exaltation to get a Charon's Gambit iota on the stack, then I can't do anything with it.
Executing it with Hermes' Gambit just stops Hermes' Gambit.

My proposal is, that if you use Hermes' Gambit to execute a single pattern (not a list with a single pattern, just a pattern), then it executes it in the current context and is able to stop the "parent" hex.

**Comment by beholderface** [comment]
You have indeed missed something.
Executing a single pattern with Hermes does not create a new execution block internally, and as such executing a single Charon's pattern (not in a list) will end the execution block that triggered the Hermes, rather than just ending the Hermes.
It's not a complete "make this hex stop *everything* it's doing", depending on how complex the hex is, but if you want to do that you can just cause a mishap.

**Comment by TheOriginalArkless** [comment]
I thought I tried exactly that and it failed. Maybe my version was too old, maybe my setup was flawed. Anyways, thanks for your reply! I will try this again at some point.
