### ISSUE TITLE
Conjure light/block should throw the invalid block mishap when they can't be placed

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/HexMod#72]
right now it does nothing

**Comment by Manonox** [comment]
Revert this, this is literally useless

**Comment by object-Object** [comment]
no

**Comment by Manonox** [comment]
> no

Tell me one thing this adds to the mod, like, this kinda doesn't let you make a 100% consistent "Wall" spell or something similar
There's no mishap detection right now as I believe AND you can't check if a block will prevent block/light placement
For some reason it works fine for `Break Block` when it targets air, but here it shits itself

**Comment by object-Object** [comment]
You could cast Break Block first if you want it to be consistent, or use addons to check the block type or catch the mishap.

**Comment by object-Object** [comment]
As a side note, coming into someone else's project and commenting on a very old issue to rudely order them without any justification to change something that's been in place for several years isn't a very polite or effective way to get things to happen.

**Comment by Manonox** [comment]
> As a side note, coming into someone else's project and commenting on a very old issue to rudely order them without any justification to change something that's been in place for several years isn't a very polite or effective way to get things to happen.

Yeah, not polite, sorry about that, but might be more effective than you think
`Break Block` variant just makes it a "i want to ruin my base/landscape by accident" spell
Addons are a valid solution, but they aren't always available (versions, modloaders, etc.), and, imo, letting it silently fail just like `Break Block` with air only expands the vanilla range of useful spells a player can make

**Comment by object-Object** [comment]
That's fair. I think a solution that fits better into how Hex tends to work could be a pattern that pushes true/false depending if it's possible to place a block at a given position, like how Scribe's Reflection can be error-checked with [Auditor's Reflection](https://hexcasting.hexxy.media/v/0.11.2/1.0/en_us/#patterns/readwrite@hexcasting:readable).

Something else you could do in vanilla Hex as a workaround is to cast [Archer's Distillation](https://hexcasting.hexxy.media/v/0.11.2/1.0/en_us/#patterns/basics@hexcasting:raycast) from within the block and check if the result is the same as the block position; if it is, there's a solid block there. It wouldn't be 100% reliable, though, since it wouldn't detect eg. sugar cane.

**Comment by Manonox** [comment]
I'll create a separate suggestion issue for a "can place" pattern a bit later
Cool idea for a workaround though, at least that helps with the base ruining part quite a bit (can also raycast from corner to corner, to detect more blocks, or even all 6 diagonals lol)
